version: '3.9'
# Define os serviços utilizados
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb
# Cria a rede de comunicação (Bridge)     
networks:
  compose-bridge:
    driver: bridge